version: "3.7"

services: 
    db:
        image: couchdb:2.3.1
        ports: 
            - "5984:5984"
        environment: 
            - "COUCHDB_USER=${COUCHDB_USER}"
            - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD}"
    s3:
        image: minio/minio:RELEASE.2020-02-07T23-28-16Z
        ports: 
            - "9000:9000"
        command: server /data
        environment: 
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    
    rabbitmq:
        image: rabbitmq:3.7-alpine

    app:
        build: ../mb.py/
        volumes: 
            - ../mb.py/:/src/
        depends_on: 
            - rabbitmq
            - db
            - s3
        ports:
            - "8000:8000"
        environment: 
            PYTHONUNBUFFERED: 0
        command: python -m medblocks.run
    
    test:
        depends_on:
            - app
        build: .
        volumes: 
            - .:/src/
        command: npm test
